name: Go Build Validation

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile cover.txt -covermode=atomic
      
    - name: Codecov
      uses: codecov/codecov-action@v1.3.1
      with:
        file: ./cover.txt
        flags: unittests
        name: codecov-umbrella


