name: Go Build 

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [main]
    
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Lint Code Base
      if: github.ref != 'refs/heads/main'
      uses: github/super-linter@v4
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: main
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Build
      if: github.ref != 'refs/heads/main'
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -coverprofile cover.txt -covermode=atomic
      
    - name: Codecov
      uses: codecov/codecov-action@v1.3.1
      with:
        file: ./cover.txt
        flags: unittests
        name: codecov-umbrella


